FROM zamora/r-devtools

# Install any other packages that I commonly use
RUN install2.r --error \
  DBI \
  dplyr \
  ggplot2 \
  httr \
  jsonlite \
  lubridate \
  purrr \
  readr \
  rstan \
  tibble \
  tidyr \
  xml2

